name: tc_gen_app
channels:
  - defaults
  - robostack-humble
  - robostack
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - expat=2.7.4=h7354ed3_0
  - icu=78.2=h33c6efd_0
  - lark-parser=0.12.0=pyhd8ed1ab_1
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20250512.1=cxx17_hba17884_0
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libev=4.33=hd590300_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.0=h5eee18b_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - nodejs=25.2.1=h728ac57_2
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=py311h06a4308_1
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - python_abi=3.11=2_cp311
  - pyyaml=6.0.3=py311h3778330_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py311h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - click==8.3.1
      - coverage==7.13.3
      - iniconfig==2.3.0
      - pluggy==1.6.0
      - pygments==2.19.2
      - pytest==9.0.2
      - pytest-cov==7.0.0
prefix: /home/aravind/anaconda3/envs/tc_gen_app
